<?xml version="1.0" encoding="utf-8"?><Database Name="Grading_System" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BLAKE\SQLEXPRESS;Initial Catalog=Grading_System;Integrated Security=True" SettingsObjectName="Int_GradeSystem.Properties.Settings" SettingsPropertyName="Grading_SystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Admin" Member="tbl_Admins">
    <Type Name="tbl_Admin">
      <Column Name="adminId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin_User" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="admin_Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TeacherAcc" Member="tbl_TeacherAccs">
    <Type Name="tbl_TeacherAcc">
      <Column Name="teacherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="teacher_password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_TeacherAcc_tbl_TeacherInfo" Member="tbl_TeacherInfos" ThisKey="teacherId" OtherKey="FK_teacherId" Type="tbl_TeacherInfo" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TeacherInfo" Member="tbl_TeacherInfos">
    <Type Name="tbl_TeacherInfo">
      <Column Name="middleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_teacherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="" Member="Property" Type="System.String" CanBeNull="false" />
      <Association Name="tbl_TeacherAcc_tbl_TeacherInfo" Member="tbl_TeacherAcc" ThisKey="FK_teacherId" OtherKey="teacherId" Type="tbl_TeacherAcc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Grading_Period" Member="tbl_Grading_Periods">
    <Type Name="tbl_Grading_Period">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstGrading_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="SecondGraing_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ThirdGrading_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FourthGrading_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="overall" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Grading_Period" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Students" Member="tbl_Students">
    <Type Name="tbl_Student">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="section" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="First_Grading" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Second_Grading" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Third_Grading" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Fourth_Grading" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy_f1" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UpdatedBy_sc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UpdatedBy_th" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UpdatedBy_f4" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Grading_Period" Member="tbl_Grading_Periods" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Grading_Period" />
      <Association Name="tbl_Student_tbl_Student_FirstG_Subject" Member="tbl_Student_FirstG_Subjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_FirstG_Subject" />
      <Association Name="tbl_Student_tbl_Student_FourthG_Subject" Member="tbl_Student_FourthG_Subjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_FourthG_Subject" />
      <Association Name="tbl_Student_tbl_Student_SecondG_Subject" Member="tbl_Student_SecondG_Subjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_SecondG_Subject" />
      <Association Name="tbl_Student_tbl_Student_ThirdG_Subject" Member="tbl_Student_ThirdG_Subjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_ThirdG_Subject" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_FirstG_Subject" Member="tbl_Student_FirstG_Subjects">
    <Type Name="tbl_Student_FirstG_Subject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_firstG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_firstG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_firstG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_firstG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_firstG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_firstG" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_firstG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GradeStatus" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_FirstG_Subject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_FourthG_Subject" Member="tbl_Student_FourthG_Subjects">
    <Type Name="tbl_Student_FourthG_Subject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_FourthG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_FourthG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_FourthG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_FourthG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_FourthG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_FourthG" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_FourthG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GradeStatus" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_FourthG_Subject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_SecondG_Subject" Member="tbl_Student_SecondG_Subjects">
    <Type Name="tbl_Student_SecondG_Subject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_SecondG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_SecondG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_SecondG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_SecondG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_SecondG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_SecondG" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_SecondG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GradeStatus" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_SecondG_Subject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_ThirdG_Subject" Member="tbl_Student_ThirdG_Subjects">
    <Type Name="tbl_Student_ThirdG_Subject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_ThirdG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_ThirdG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_ThirdG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_ThirdG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_ThirdG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_ThirdG" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_ThirdG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GradeStatus" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_ThirdG_Subject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_View_TeacherAcc" Method="SP_View_TeacherAcc">
    <ElementType Name="SP_View_TeacherAccResult">
      <Column Name="[Teacher ID]" Member="Teacher_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passowrd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_adm_TeacherUpdatePass" Method="SP_adm_TeacherUpdatePass">
    <Parameter Name="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="teacher_password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_DeleteAccount" Method="SP_adm_DeleteAccount">
    <Parameter Name="teacherID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_Create_TeacherAcc" Method="SP_adm_Create_TeacherAcc">
    <Parameter Name="firstname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_UpateInfo" Method="SP_tch_UpateInfo">
    <Parameter Name="middleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="phoneNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="FK_ID" Parameter="fK_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_DeleteAccountBothTables" Method="SP_adm_DeleteAccountBothTables">
    <Parameter Name="teacherID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_TeacherUpdatePass" Method="SP_tch_TeacherUpdatePass">
    <Parameter Name="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="teacher_password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Add_Students" Method="SP_stud_Add_Students">
    <Parameter Name="fname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mname" Parameter="mname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Bdate" Parameter="bdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="section" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="createdBy" Type="System.String" DbType="NVarChar(75)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Ranking_FirstGrading" Method="SP_stud_Ranking_FirstGrading">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_Ranking_FirstGradingResult">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_Ranking_ThirdGrading" Method="SP_stud_Ranking_ThirdGrading">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_Ranking_ThirdGradingResult">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_Ranking_FourthGrading" Method="SP_stud_Ranking_FourthGrading">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_Ranking_FourthGradingResult">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_Ranking_SecondGrading" Method="SP_stud_Ranking_SecondGrading">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_Ranking_SecondGradingResult">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_ViewLIst" Method="SP_stud_ViewLIst">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_ViewLIstResult">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_Grading_Avg" Method="SP_stud_Grading_Avg">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="First_Avg" Parameter="first_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Second_Avg" Parameter="second_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Third_Avg" Parameter="third_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Fourth_Avg" Parameter="fourth_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="Overall" Parameter="overall" Type="System.Single" DbType="Real" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_InputGrades_FirstGrading" Method="SP_stud_InputGrades_FirstGrading">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="FirstG_Avg" Parameter="firstG_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_InputGrades_SecondGrading" Method="SP_stud_InputGrades_SecondGrading">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="SecondG_Avg" Parameter="secondG_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_DeleteStudent" Method="SP_tch_DeleteStudent">
    <Parameter Name="studentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_ViewStudents" Method="SP_stud_ViewStudents">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_ViewStudentsResult">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Full Name]" Member="Full_Name" Type="System.String" DbType="NVarChar(153) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[First Grading|Uptd by]" Member="First_Grading_Uptd_by" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="[Second Grading|Uptd by]" Member="Second_Grading_Uptd_by" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="[Third Grading|Uptd by]" Member="Third_Grading_Uptd_by" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="[Fourth Grading|Uptd by]" Member="Fourth_Grading_Uptd_by" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_InputGrades_ThirdGrading" Method="SP_stud_InputGrades_ThirdGrading">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="ThirdG_Avg" Parameter="thirdG_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_InputGrades_FourthGrading" Method="SP_stud_InputGrades_FourthGrading">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="FourthG_Avg" Parameter="fourthG_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>