<?xml version="1.0" encoding="utf-8"?><Database Name="Grading_System" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BLAKE\SQLEXPRESS;Initial Catalog=Grading_System;Integrated Security=True" SettingsObjectName="Int_GradeSystem.Properties.Settings" SettingsPropertyName="Grading_SystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Admin" Member="tbl_Admins">
    <Type Name="tbl_Admin">
      <Column Name="adminId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin_User" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="admin_Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TeacherAcc" Member="tbl_TeacherAccs">
    <Type Name="tbl_TeacherAcc">
      <Column Name="teacherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="teacher_password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_TeacherAcc_tbl_TeacherInfo" Member="tbl_TeacherInfos" ThisKey="teacherId" OtherKey="FK_teacherId" Type="tbl_TeacherInfo" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TeacherInfo" Member="tbl_TeacherInfos">
    <Type Name="tbl_TeacherInfo">
      <Column Name="middleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_teacherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_TeacherAcc_tbl_TeacherInfo" Member="tbl_TeacherAcc" ThisKey="FK_teacherId" OtherKey="teacherId" Type="tbl_TeacherAcc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Students" Member="tbl_Students">
    <Type Name="tbl_Student">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="section" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Student_tbl_Student_FinalSubject" Member="tbl_Student_FinalSubjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_FinalSubject" />
      <Association Name="tbl_Student_tbl_Student_PrelimSubject" Member="tbl_Student_PrelimSubjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_PrelimSubject" />
      <Association Name="tbl_Student_tbl_Student_MidtermSubject" Member="tbl_Student_MidtermSubjects" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Student_MidtermSubject" />
      <Association Name="tbl_Student_tbl_Grading_Period" Member="tbl_Grading_Periods" ThisKey="studentId" OtherKey="FK_studentID" Type="tbl_Grading_Period" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_FinalSubject" Member="tbl_Student_FinalSubjects">
    <Type Name="tbl_Student_FinalSubject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_Final" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_Final" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_Final" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_Final" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_Final" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_Final" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_Final" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_FinalSubject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_PrelimSubject" Member="tbl_Student_PrelimSubjects">
    <Type Name="tbl_Student_PrelimSubject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_Prelim" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_Prelim" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_Prelim" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_Prelim" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_Prelim" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_Prelim" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_Prelim" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_PrelimSubject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student_MidtermSubject" Member="tbl_Student_MidtermSubjects">
    <Type Name="tbl_Student_MidtermSubject">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mapeh_Midterm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="English_Midterm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Math_Midterm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Filipino_Midterm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Science_Midterm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Period_Avg_Midterm" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Period_Status_MIdterm" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Student_MidtermSubject" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Grading_Period" Member="tbl_Grading_Periods">
    <Type Name="tbl_Grading_Period">
      <Column Name="FK_studentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prelim_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="midterm_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="final_avg" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="overall" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="tbl_Student_tbl_Grading_Period" Member="tbl_Student" ThisKey="FK_studentID" OtherKey="studentId" Type="tbl_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_View_TeacherAcc" Method="SP_View_TeacherAcc">
    <ElementType Name="SP_View_TeacherAccResult">
      <Column Name="[Teacher ID]" Member="Teacher_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passowrd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_adm_TeacherUpdatePass" Method="SP_adm_TeacherUpdatePass">
    <Parameter Name="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="teacher_password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_DeleteAccount" Method="SP_adm_DeleteAccount">
    <Parameter Name="teacherID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_Create_TeacherAcc" Method="SP_adm_Create_TeacherAcc">
    <Parameter Name="firstname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_UpateInfo" Method="SP_tch_UpateInfo">
    <Parameter Name="middleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="phoneNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="FK_ID" Parameter="fK_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_adm_DeleteAccountBothTables" Method="SP_adm_DeleteAccountBothTables">
    <Parameter Name="teacherID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_TeacherUpdatePass" Method="SP_tch_TeacherUpdatePass">
    <Parameter Name="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="teacher_password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_tch_DeleteStudent" Method="SP_tch_DeleteStudent">
    <Parameter Name="studentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tbl_name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Add_Students" Method="SP_stud_Add_Students">
    <Parameter Name="fname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mname" Parameter="mname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Bdate" Parameter="bdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="section" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="createdBy" Type="System.String" DbType="NVarChar(75)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_View_Students" Method="SP_stud_View_Students">
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_stud_View_StudentsResult">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="section" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_stud_Prelim_InputGrades" Method="SP_stud_Prelim_InputGrades">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="Prelim_Avg" Parameter="prelim_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Final_InputGrades" Method="SP_stud_Final_InputGrades">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="Prelim_Avg" Parameter="prelim_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Midterm_InputGrades" Method="SP_stud_Midterm_InputGrades">
    <Parameter Name="Mapeh" Parameter="mapeh" Type="System.Double" DbType="Float" />
    <Parameter Name="English" Parameter="english" Type="System.Double" DbType="Float" />
    <Parameter Name="Math" Parameter="math" Type="System.Double" DbType="Float" />
    <Parameter Name="Filipino" Parameter="filipino" Type="System.Double" DbType="Float" />
    <Parameter Name="Science" Parameter="science" Type="System.Double" DbType="Float" />
    <Parameter Name="Prelim_Avg" Parameter="prelim_Avg" Type="System.Double" DbType="Float" />
    <Parameter Name="Student_status" Parameter="student_status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Teacher" Parameter="teacher" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_stud_Grading_Avg" Method="SP_stud_Grading_Avg">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Prelim_Avg" Parameter="prelim_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Midterm_Avg" Parameter="midterm_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Final_Avg" Parameter="final_Avg" Type="System.Single" DbType="Real" />
    <Parameter Name="Overall" Parameter="overall" Type="System.Single" DbType="Real" />
    <Return Type="System.Int32" />
  </Function>
</Database>