#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Int_GradeSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Grading_System")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Admin(tbl_Admin instance);
    partial void Updatetbl_Admin(tbl_Admin instance);
    partial void Deletetbl_Admin(tbl_Admin instance);
    partial void Inserttbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Updatetbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Deletetbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Inserttbl_Student(tbl_Student instance);
    partial void Updatetbl_Student(tbl_Student instance);
    partial void Deletetbl_Student(tbl_Student instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Int_GradeSystem.Properties.Settings.Default.Grading_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Admin> tbl_Admins
		{
			get
			{
				return this.GetTable<tbl_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TeacherAcc> tbl_TeacherAccs
		{
			get
			{
				return this.GetTable<tbl_TeacherAcc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TeacherInfo> tbl_TeacherInfos
		{
			get
			{
				return this.GetTable<tbl_TeacherInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student> tbl_Students
		{
			get
			{
				return this.GetTable<tbl_Student>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_FinalSubject> tbl_Student_FinalSubjects
		{
			get
			{
				return this.GetTable<tbl_Student_FinalSubject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_PrelimSubject> tbl_Student_PrelimSubjects
		{
			get
			{
				return this.GetTable<tbl_Student_PrelimSubject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_MidtermSubject> tbl_Student_MidtermSubjects
		{
			get
			{
				return this.GetTable<tbl_Student_MidtermSubject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Grading_Period> tbl_Grading_Periods
		{
			get
			{
				return this.GetTable<tbl_Grading_Period>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_View_TeacherAcc")]
		public ISingleResult<SP_View_TeacherAccResult> SP_View_TeacherAcc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_View_TeacherAccResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_TeacherUpdatePass")]
		public int SP_adm_TeacherUpdatePass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string teacher_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherId, teacher_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_DeleteAccount")]
		public int SP_adm_DeleteAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_Create_TeacherAcc")]
		public int SP_adm_Create_TeacherAcc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, lastname, email, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_UpateInfo")]
		public int SP_tch_UpateInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string middleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> birthDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_ID", DbType="Int")] System.Nullable<int> fK_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), middleName, gender, birthDate, age, phoneNumber, fK_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_DeleteAccountBothTables")]
		public int SP_adm_DeleteAccountBothTables([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_TeacherUpdatePass")]
		public int SP_tch_TeacherUpdatePass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string teacher_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherId, teacher_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_DeleteStudent")]
		public int SP_tch_DeleteStudent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> studentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tbl_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID, tbl_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Add_Students")]
		public int SP_stud_Add_Students([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="NVarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bdate", DbType="Date")] System.Nullable<System.DateTime> bdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string section, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(75)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, mname, gender, bdate, age, grade, section, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_View_Students")]
		public ISingleResult<SP_stud_View_StudentsResult> SP_stud_View_Students([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_View_StudentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Prelim_InputGrades")]
		public int SP_stud_Prelim_InputGrades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prelim_Avg", DbType="Float")] System.Nullable<double> prelim_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, prelim_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Final_InputGrades")]
		public int SP_stud_Final_InputGrades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prelim_Avg", DbType="Float")] System.Nullable<double> prelim_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, prelim_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Midterm_InputGrades")]
		public int SP_stud_Midterm_InputGrades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prelim_Avg", DbType="Float")] System.Nullable<double> prelim_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, prelim_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Grading_Avg")]
		public int SP_stud_Grading_Avg([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prelim_Avg", DbType="Real")] System.Nullable<float> prelim_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Midterm_Avg", DbType="Real")] System.Nullable<float> midterm_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Final_Avg", DbType="Real")] System.Nullable<float> final_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Overall", DbType="Real")] System.Nullable<float> overall)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentId, prelim_Avg, midterm_Avg, final_Avg, overall);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admin")]
	public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _adminId;
		
		private string _admin_User;
		
		private string _admin_Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminIdChanging(int value);
    partial void OnadminIdChanged();
    partial void Onadmin_UserChanging(string value);
    partial void Onadmin_UserChanged();
    partial void Onadmin_PassChanging(string value);
    partial void Onadmin_PassChanged();
    #endregion
		
		public tbl_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int adminId
		{
			get
			{
				return this._adminId;
			}
			set
			{
				if ((this._adminId != value))
				{
					this.OnadminIdChanging(value);
					this.SendPropertyChanging();
					this._adminId = value;
					this.SendPropertyChanged("adminId");
					this.OnadminIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_User", DbType="NVarChar(50)")]
		public string admin_User
		{
			get
			{
				return this._admin_User;
			}
			set
			{
				if ((this._admin_User != value))
				{
					this.Onadmin_UserChanging(value);
					this.SendPropertyChanging();
					this._admin_User = value;
					this.SendPropertyChanged("admin_User");
					this.Onadmin_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_Pass", DbType="NVarChar(50)")]
		public string admin_Pass
		{
			get
			{
				return this._admin_Pass;
			}
			set
			{
				if ((this._admin_Pass != value))
				{
					this.Onadmin_PassChanging(value);
					this.SendPropertyChanging();
					this._admin_Pass = value;
					this.SendPropertyChanged("admin_Pass");
					this.Onadmin_PassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TeacherAcc")]
	public partial class tbl_TeacherAcc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teacherId;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _email;
		
		private string _teacher_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnteacherIdChanging(int value);
    partial void OnteacherIdChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onteacher_passwordChanging(string value);
    partial void Onteacher_passwordChanged();
    #endregion
		
		public tbl_TeacherAcc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teacherId
		{
			get
			{
				return this._teacherId;
			}
			set
			{
				if ((this._teacherId != value))
				{
					this.OnteacherIdChanging(value);
					this.SendPropertyChanging();
					this._teacherId = value;
					this.SendPropertyChanged("teacherId");
					this.OnteacherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(50)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_password", DbType="NVarChar(50)")]
		public string teacher_password
		{
			get
			{
				return this._teacher_password;
			}
			set
			{
				if ((this._teacher_password != value))
				{
					this.Onteacher_passwordChanging(value);
					this.SendPropertyChanging();
					this._teacher_password = value;
					this.SendPropertyChanged("teacher_password");
					this.Onteacher_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TeacherInfo")]
	public partial class tbl_TeacherInfo
	{
		
		private string _middleName;
		
		private string _gender;
		
		private System.Nullable<System.DateTime> _birthDate;
		
		private System.Nullable<int> _age;
		
		private string _phoneNumber;
		
		private System.Nullable<int> _FK_teacherId;
		
		public tbl_TeacherInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="NVarChar(50)")]
		public string middleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				if ((this._middleName != value))
				{
					this._middleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(30)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="Date")]
		public System.Nullable<System.DateTime> birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this._birthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(50)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_teacherId", DbType="Int")]
		public System.Nullable<int> FK_teacherId
		{
			get
			{
				return this._FK_teacherId;
			}
			set
			{
				if ((this._FK_teacherId != value))
				{
					this._FK_teacherId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Students")]
	public partial class tbl_Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studentId;
		
		private string _firstName;
		
		private string _middleName;
		
		private string _lastName;
		
		private System.Nullable<int> _age;
		
		private string _gender;
		
		private System.DateTime _birthDate;
		
		private System.Nullable<int> _grade;
		
		private string _section;
		
		private string _CreatedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIdChanging(int value);
    partial void OnstudentIdChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnmiddleNameChanging(string value);
    partial void OnmiddleNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnbirthDateChanging(System.DateTime value);
    partial void OnbirthDateChanged();
    partial void OngradeChanging(System.Nullable<int> value);
    partial void OngradeChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    #endregion
		
		public tbl_Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this.OnstudentIdChanging(value);
					this.SendPropertyChanging();
					this._studentId = value;
					this.SendPropertyChanged("studentId");
					this.OnstudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string middleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				if ((this._middleName != value))
				{
					this.OnmiddleNameChanging(value);
					this.SendPropertyChanging();
					this._middleName = value;
					this.SendPropertyChanged("middleName");
					this.OnmiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(30)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="Date NOT NULL")]
		public System.DateTime birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this.OnbirthDateChanging(value);
					this.SendPropertyChanging();
					this._birthDate = value;
					this.SendPropertyChanged("birthDate");
					this.OnbirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(30)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this.OnsectionChanging(value);
					this.SendPropertyChanging();
					this._section = value;
					this.SendPropertyChanged("section");
					this.OnsectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_FinalSubject")]
	public partial class tbl_Student_FinalSubject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_Final;
		
		private System.Nullable<double> _English_Final;
		
		private System.Nullable<double> _Math_Final;
		
		private System.Nullable<double> _Filipino_Final;
		
		private System.Nullable<double> _Science_Final;
		
		private System.Nullable<float> _Period_Avg_Final;
		
		private string _Period_Status_Final;
		
		private string _updatedBy;
		
		public tbl_Student_FinalSubject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_Final", DbType="Float")]
		public System.Nullable<double> Mapeh_Final
		{
			get
			{
				return this._Mapeh_Final;
			}
			set
			{
				if ((this._Mapeh_Final != value))
				{
					this._Mapeh_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_Final", DbType="Float")]
		public System.Nullable<double> English_Final
		{
			get
			{
				return this._English_Final;
			}
			set
			{
				if ((this._English_Final != value))
				{
					this._English_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_Final", DbType="Float")]
		public System.Nullable<double> Math_Final
		{
			get
			{
				return this._Math_Final;
			}
			set
			{
				if ((this._Math_Final != value))
				{
					this._Math_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_Final", DbType="Float")]
		public System.Nullable<double> Filipino_Final
		{
			get
			{
				return this._Filipino_Final;
			}
			set
			{
				if ((this._Filipino_Final != value))
				{
					this._Filipino_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_Final", DbType="Float")]
		public System.Nullable<double> Science_Final
		{
			get
			{
				return this._Science_Final;
			}
			set
			{
				if ((this._Science_Final != value))
				{
					this._Science_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_Final", DbType="Real")]
		public System.Nullable<float> Period_Avg_Final
		{
			get
			{
				return this._Period_Avg_Final;
			}
			set
			{
				if ((this._Period_Avg_Final != value))
				{
					this._Period_Avg_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_Final", DbType="NVarChar(30)")]
		public string Period_Status_Final
		{
			get
			{
				return this._Period_Status_Final;
			}
			set
			{
				if ((this._Period_Status_Final != value))
				{
					this._Period_Status_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_PrelimSubject")]
	public partial class tbl_Student_PrelimSubject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_Prelim;
		
		private System.Nullable<double> _English_Prelim;
		
		private System.Nullable<double> _Math_Prelim;
		
		private System.Nullable<double> _Filipino_Prelim;
		
		private System.Nullable<double> _Science_Prelim;
		
		private System.Nullable<float> _Period_Avg_Prelim;
		
		private string _Period_Status_Prelim;
		
		private string _updatedBy;
		
		public tbl_Student_PrelimSubject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_Prelim", DbType="Float")]
		public System.Nullable<double> Mapeh_Prelim
		{
			get
			{
				return this._Mapeh_Prelim;
			}
			set
			{
				if ((this._Mapeh_Prelim != value))
				{
					this._Mapeh_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_Prelim", DbType="Float")]
		public System.Nullable<double> English_Prelim
		{
			get
			{
				return this._English_Prelim;
			}
			set
			{
				if ((this._English_Prelim != value))
				{
					this._English_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_Prelim", DbType="Float")]
		public System.Nullable<double> Math_Prelim
		{
			get
			{
				return this._Math_Prelim;
			}
			set
			{
				if ((this._Math_Prelim != value))
				{
					this._Math_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_Prelim", DbType="Float")]
		public System.Nullable<double> Filipino_Prelim
		{
			get
			{
				return this._Filipino_Prelim;
			}
			set
			{
				if ((this._Filipino_Prelim != value))
				{
					this._Filipino_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_Prelim", DbType="Float")]
		public System.Nullable<double> Science_Prelim
		{
			get
			{
				return this._Science_Prelim;
			}
			set
			{
				if ((this._Science_Prelim != value))
				{
					this._Science_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_Prelim", DbType="Real")]
		public System.Nullable<float> Period_Avg_Prelim
		{
			get
			{
				return this._Period_Avg_Prelim;
			}
			set
			{
				if ((this._Period_Avg_Prelim != value))
				{
					this._Period_Avg_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_Prelim", DbType="NVarChar(30)")]
		public string Period_Status_Prelim
		{
			get
			{
				return this._Period_Status_Prelim;
			}
			set
			{
				if ((this._Period_Status_Prelim != value))
				{
					this._Period_Status_Prelim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_MidtermSubject")]
	public partial class tbl_Student_MidtermSubject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_Midterm;
		
		private System.Nullable<double> _English_Midterm;
		
		private System.Nullable<double> _Math_Midterm;
		
		private System.Nullable<double> _Filipino_Midterm;
		
		private System.Nullable<double> _Science_Midterm;
		
		private System.Nullable<float> _Period_Avg_Midterm;
		
		private string _Period_Status_MIdterm;
		
		private string _updatedBy;
		
		public tbl_Student_MidtermSubject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_Midterm", DbType="Float")]
		public System.Nullable<double> Mapeh_Midterm
		{
			get
			{
				return this._Mapeh_Midterm;
			}
			set
			{
				if ((this._Mapeh_Midterm != value))
				{
					this._Mapeh_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_Midterm", DbType="Float")]
		public System.Nullable<double> English_Midterm
		{
			get
			{
				return this._English_Midterm;
			}
			set
			{
				if ((this._English_Midterm != value))
				{
					this._English_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_Midterm", DbType="Float")]
		public System.Nullable<double> Math_Midterm
		{
			get
			{
				return this._Math_Midterm;
			}
			set
			{
				if ((this._Math_Midterm != value))
				{
					this._Math_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_Midterm", DbType="Float")]
		public System.Nullable<double> Filipino_Midterm
		{
			get
			{
				return this._Filipino_Midterm;
			}
			set
			{
				if ((this._Filipino_Midterm != value))
				{
					this._Filipino_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_Midterm", DbType="Float")]
		public System.Nullable<double> Science_Midterm
		{
			get
			{
				return this._Science_Midterm;
			}
			set
			{
				if ((this._Science_Midterm != value))
				{
					this._Science_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_Midterm", DbType="Real")]
		public System.Nullable<float> Period_Avg_Midterm
		{
			get
			{
				return this._Period_Avg_Midterm;
			}
			set
			{
				if ((this._Period_Avg_Midterm != value))
				{
					this._Period_Avg_Midterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_MIdterm", DbType="NVarChar(30)")]
		public string Period_Status_MIdterm
		{
			get
			{
				return this._Period_Status_MIdterm;
			}
			set
			{
				if ((this._Period_Status_MIdterm != value))
				{
					this._Period_Status_MIdterm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Grading_Period")]
	public partial class tbl_Grading_Period
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<float> _prelim_avg;
		
		private System.Nullable<float> _midterm_avg;
		
		private System.Nullable<float> _final_avg;
		
		private System.Nullable<float> _overall;
		
		public tbl_Grading_Period()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prelim_avg", DbType="Real")]
		public System.Nullable<float> prelim_avg
		{
			get
			{
				return this._prelim_avg;
			}
			set
			{
				if ((this._prelim_avg != value))
				{
					this._prelim_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_midterm_avg", DbType="Real")]
		public System.Nullable<float> midterm_avg
		{
			get
			{
				return this._midterm_avg;
			}
			set
			{
				if ((this._midterm_avg != value))
				{
					this._midterm_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_avg", DbType="Real")]
		public System.Nullable<float> final_avg
		{
			get
			{
				return this._final_avg;
			}
			set
			{
				if ((this._final_avg != value))
				{
					this._final_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall", DbType="Real")]
		public System.Nullable<float> overall
		{
			get
			{
				return this._overall;
			}
			set
			{
				if ((this._overall != value))
				{
					this._overall = value;
				}
			}
		}
	}
	
	public partial class SP_View_TeacherAccResult
	{
		
		private int _Teacher_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Passowrd;
		
		public SP_View_TeacherAccResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Teacher ID]", Storage="_Teacher_ID", DbType="Int NOT NULL")]
		public int Teacher_ID
		{
			get
			{
				return this._Teacher_ID;
			}
			set
			{
				if ((this._Teacher_ID != value))
				{
					this._Teacher_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passowrd", DbType="NVarChar(50)")]
		public string Passowrd
		{
			get
			{
				return this._Passowrd;
			}
			set
			{
				if ((this._Passowrd != value))
				{
					this._Passowrd = value;
				}
			}
		}
	}
	
	public partial class SP_stud_View_StudentsResult
	{
		
		private int _studentId;
		
		private string _firstName;
		
		private string _middleName;
		
		private string _lastName;
		
		private System.Nullable<int> _age;
		
		private string _gender;
		
		private System.DateTime _birthDate;
		
		private System.Nullable<int> _grade;
		
		private string _section;
		
		private string _CreatedBy;
		
		public SP_stud_View_StudentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", DbType="Int NOT NULL")]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this._studentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this._firstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string middleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				if ((this._middleName != value))
				{
					this._middleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this._lastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(30)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="Date NOT NULL")]
		public System.DateTime birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this._birthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this._grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(30)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this._section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
