#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Int_GradeSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Grading_System")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Admin(tbl_Admin instance);
    partial void Updatetbl_Admin(tbl_Admin instance);
    partial void Deletetbl_Admin(tbl_Admin instance);
    partial void Inserttbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Updatetbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Deletetbl_TeacherAcc(tbl_TeacherAcc instance);
    partial void Inserttbl_Student(tbl_Student instance);
    partial void Updatetbl_Student(tbl_Student instance);
    partial void Deletetbl_Student(tbl_Student instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Int_GradeSystem.Properties.Settings.Default.Grading_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Admin> tbl_Admins
		{
			get
			{
				return this.GetTable<tbl_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TeacherAcc> tbl_TeacherAccs
		{
			get
			{
				return this.GetTable<tbl_TeacherAcc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TeacherInfo> tbl_TeacherInfos
		{
			get
			{
				return this.GetTable<tbl_TeacherInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Grading_Period> tbl_Grading_Periods
		{
			get
			{
				return this.GetTable<tbl_Grading_Period>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student> tbl_Students
		{
			get
			{
				return this.GetTable<tbl_Student>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_FirstG_Subject> tbl_Student_FirstG_Subjects
		{
			get
			{
				return this.GetTable<tbl_Student_FirstG_Subject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_FourthG_Subject> tbl_Student_FourthG_Subjects
		{
			get
			{
				return this.GetTable<tbl_Student_FourthG_Subject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_SecondG_Subject> tbl_Student_SecondG_Subjects
		{
			get
			{
				return this.GetTable<tbl_Student_SecondG_Subject>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Student_ThirdG_Subject> tbl_Student_ThirdG_Subjects
		{
			get
			{
				return this.GetTable<tbl_Student_ThirdG_Subject>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_View_TeacherAcc")]
		public ISingleResult<SP_View_TeacherAccResult> SP_View_TeacherAcc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_View_TeacherAccResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_TeacherUpdatePass")]
		public int SP_adm_TeacherUpdatePass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string teacher_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherId, teacher_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_DeleteAccount")]
		public int SP_adm_DeleteAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_Create_TeacherAcc")]
		public int SP_adm_Create_TeacherAcc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, lastname, email, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_UpateInfo")]
		public int SP_tch_UpateInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string middleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> birthDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_ID", DbType="Int")] System.Nullable<int> fK_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), middleName, gender, birthDate, age, phoneNumber, fK_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_adm_DeleteAccountBothTables")]
		public int SP_adm_DeleteAccountBothTables([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_TeacherUpdatePass")]
		public int SP_tch_TeacherUpdatePass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> teacherId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string teacher_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), teacherId, teacher_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Add_Students")]
		public int SP_stud_Add_Students([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="NVarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bdate", DbType="Date")] System.Nullable<System.DateTime> bdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string section, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(75)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, mname, gender, bdate, age, grade, section, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Ranking_FirstGrading")]
		public ISingleResult<SP_stud_Ranking_FirstGradingResult> SP_stud_Ranking_FirstGrading([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_Ranking_FirstGradingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Ranking_ThirdGrading")]
		public ISingleResult<SP_stud_Ranking_ThirdGradingResult> SP_stud_Ranking_ThirdGrading([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_Ranking_ThirdGradingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Ranking_FourthGrading")]
		public ISingleResult<SP_stud_Ranking_FourthGradingResult> SP_stud_Ranking_FourthGrading([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_Ranking_FourthGradingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Ranking_SecondGrading")]
		public ISingleResult<SP_stud_Ranking_SecondGradingResult> SP_stud_Ranking_SecondGrading([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_Ranking_SecondGradingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_ViewLIst")]
		public ISingleResult<SP_stud_ViewLIstResult> SP_stud_ViewLIst([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_ViewLIstResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_Grading_Avg")]
		public int SP_stud_Grading_Avg([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="First_Avg", DbType="Real")] System.Nullable<float> first_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Second_Avg", DbType="Real")] System.Nullable<float> second_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Third_Avg", DbType="Real")] System.Nullable<float> third_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fourth_Avg", DbType="Real")] System.Nullable<float> fourth_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Overall", DbType="Real")] System.Nullable<float> overall)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentId, first_Avg, second_Avg, third_Avg, fourth_Avg, grade, overall);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_InputGrades_FirstGrading")]
		public int SP_stud_InputGrades_FirstGrading([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstG_Avg", DbType="Float")] System.Nullable<double> firstG_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, firstG_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_InputGrades_ThirdGrading")]
		public int SP_stud_InputGrades_ThirdGrading([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThirdG_Avg", DbType="Float")] System.Nullable<double> thirdG_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(30)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, thirdG_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_InputGrades_FourthGrading")]
		public int SP_stud_InputGrades_FourthGrading([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FourthG_Avg", DbType="Float")] System.Nullable<double> fourthG_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, fourthG_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_InputGrades_SecondGrading")]
		public int SP_stud_InputGrades_SecondGrading([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mapeh", DbType="Float")] System.Nullable<double> mapeh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="English", DbType="Float")] System.Nullable<double> english, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Math", DbType="Float")] System.Nullable<double> math, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filipino", DbType="Float")] System.Nullable<double> filipino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Science", DbType="Float")] System.Nullable<double> science, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondG_Avg", DbType="Float")] System.Nullable<double> secondG_Avg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Student_status", DbType="VarChar(50)")] string student_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentId", DbType="Int")] System.Nullable<int> studentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Teacher", DbType="NVarChar(50)")] string teacher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mapeh, english, math, filipino, science, secondG_Avg, student_status, studentId, teacher);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_tch_DeleteStudent")]
		public int SP_tch_DeleteStudent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_stud_ViewStudents")]
		public ISingleResult<SP_stud_ViewStudentsResult> SP_stud_ViewStudents([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), grade);
			return ((ISingleResult<SP_stud_ViewStudentsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admin")]
	public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _adminId;
		
		private string _admin_User;
		
		private string _admin_Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminIdChanging(int value);
    partial void OnadminIdChanged();
    partial void Onadmin_UserChanging(string value);
    partial void Onadmin_UserChanged();
    partial void Onadmin_PassChanging(string value);
    partial void Onadmin_PassChanged();
    #endregion
		
		public tbl_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int adminId
		{
			get
			{
				return this._adminId;
			}
			set
			{
				if ((this._adminId != value))
				{
					this.OnadminIdChanging(value);
					this.SendPropertyChanging();
					this._adminId = value;
					this.SendPropertyChanged("adminId");
					this.OnadminIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_User", DbType="NVarChar(50)")]
		public string admin_User
		{
			get
			{
				return this._admin_User;
			}
			set
			{
				if ((this._admin_User != value))
				{
					this.Onadmin_UserChanging(value);
					this.SendPropertyChanging();
					this._admin_User = value;
					this.SendPropertyChanged("admin_User");
					this.Onadmin_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_Pass", DbType="NVarChar(50)")]
		public string admin_Pass
		{
			get
			{
				return this._admin_Pass;
			}
			set
			{
				if ((this._admin_Pass != value))
				{
					this.Onadmin_PassChanging(value);
					this.SendPropertyChanging();
					this._admin_Pass = value;
					this.SendPropertyChanged("admin_Pass");
					this.Onadmin_PassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TeacherAcc")]
	public partial class tbl_TeacherAcc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teacherId;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _email;
		
		private string _teacher_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnteacherIdChanging(int value);
    partial void OnteacherIdChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onteacher_passwordChanging(string value);
    partial void Onteacher_passwordChanged();
    #endregion
		
		public tbl_TeacherAcc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teacherId
		{
			get
			{
				return this._teacherId;
			}
			set
			{
				if ((this._teacherId != value))
				{
					this.OnteacherIdChanging(value);
					this.SendPropertyChanging();
					this._teacherId = value;
					this.SendPropertyChanged("teacherId");
					this.OnteacherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(50)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_password", DbType="NVarChar(50)")]
		public string teacher_password
		{
			get
			{
				return this._teacher_password;
			}
			set
			{
				if ((this._teacher_password != value))
				{
					this.Onteacher_passwordChanging(value);
					this.SendPropertyChanging();
					this._teacher_password = value;
					this.SendPropertyChanged("teacher_password");
					this.Onteacher_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TeacherInfo")]
	public partial class tbl_TeacherInfo
	{
		
		private string _middleName;
		
		private string _gender;
		
		private System.Nullable<System.DateTime> _birthDate;
		
		private System.Nullable<int> _age;
		
		private string _phoneNumber;
		
		private System.Nullable<int> _FK_teacherId;
		
		public tbl_TeacherInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="NVarChar(50)")]
		public string middleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				if ((this._middleName != value))
				{
					this._middleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(30)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="Date")]
		public System.Nullable<System.DateTime> birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this._birthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(50)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_teacherId", DbType="Int")]
		public System.Nullable<int> FK_teacherId
		{
			get
			{
				return this._FK_teacherId;
			}
			set
			{
				if ((this._FK_teacherId != value))
				{
					this._FK_teacherId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Grading_Period")]
	public partial class tbl_Grading_Period
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<float> _FirstGrading_avg;
		
		private System.Nullable<float> _SecondGraing_avg;
		
		private System.Nullable<float> _ThirdGrading_avg;
		
		private System.Nullable<float> _FourthGrading_avg;
		
		private System.Nullable<float> _overall;
		
		private System.Nullable<int> _grade;
		
		public tbl_Grading_Period()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstGrading_avg", DbType="Real")]
		public System.Nullable<float> FirstGrading_avg
		{
			get
			{
				return this._FirstGrading_avg;
			}
			set
			{
				if ((this._FirstGrading_avg != value))
				{
					this._FirstGrading_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondGraing_avg", DbType="Real")]
		public System.Nullable<float> SecondGraing_avg
		{
			get
			{
				return this._SecondGraing_avg;
			}
			set
			{
				if ((this._SecondGraing_avg != value))
				{
					this._SecondGraing_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdGrading_avg", DbType="Real")]
		public System.Nullable<float> ThirdGrading_avg
		{
			get
			{
				return this._ThirdGrading_avg;
			}
			set
			{
				if ((this._ThirdGrading_avg != value))
				{
					this._ThirdGrading_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FourthGrading_avg", DbType="Real")]
		public System.Nullable<float> FourthGrading_avg
		{
			get
			{
				return this._FourthGrading_avg;
			}
			set
			{
				if ((this._FourthGrading_avg != value))
				{
					this._FourthGrading_avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall", DbType="Real")]
		public System.Nullable<float> overall
		{
			get
			{
				return this._overall;
			}
			set
			{
				if ((this._overall != value))
				{
					this._overall = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this._grade = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Students")]
	public partial class tbl_Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studentId;
		
		private string _firstName;
		
		private string _middleName;
		
		private string _lastName;
		
		private System.Nullable<int> _age;
		
		private string _gender;
		
		private System.DateTime _birthDate;
		
		private System.Nullable<int> _grade;
		
		private string _section;
		
		private string _First_Grading;
		
		private string _Second_Grading;
		
		private string _Third_Grading;
		
		private string _Fourth_Grading;
		
		private string _CreatedBy;
		
		private string _UpdatedBy_f1;
		
		private string _UpdatedBy_sc;
		
		private string _UpdatedBy_th;
		
		private string _UpdatedBy_f4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIdChanging(int value);
    partial void OnstudentIdChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnmiddleNameChanging(string value);
    partial void OnmiddleNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnbirthDateChanging(System.DateTime value);
    partial void OnbirthDateChanged();
    partial void OngradeChanging(System.Nullable<int> value);
    partial void OngradeChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    partial void OnFirst_GradingChanging(string value);
    partial void OnFirst_GradingChanged();
    partial void OnSecond_GradingChanging(string value);
    partial void OnSecond_GradingChanged();
    partial void OnThird_GradingChanging(string value);
    partial void OnThird_GradingChanged();
    partial void OnFourth_GradingChanging(string value);
    partial void OnFourth_GradingChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedBy_f1Changing(string value);
    partial void OnUpdatedBy_f1Changed();
    partial void OnUpdatedBy_scChanging(string value);
    partial void OnUpdatedBy_scChanged();
    partial void OnUpdatedBy_thChanging(string value);
    partial void OnUpdatedBy_thChanged();
    partial void OnUpdatedBy_f4Changing(string value);
    partial void OnUpdatedBy_f4Changed();
    #endregion
		
		public tbl_Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this.OnstudentIdChanging(value);
					this.SendPropertyChanging();
					this._studentId = value;
					this.SendPropertyChanged("studentId");
					this.OnstudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string middleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				if ((this._middleName != value))
				{
					this.OnmiddleNameChanging(value);
					this.SendPropertyChanging();
					this._middleName = value;
					this.SendPropertyChanged("middleName");
					this.OnmiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(30)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="Date NOT NULL")]
		public System.DateTime birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this.OnbirthDateChanging(value);
					this.SendPropertyChanging();
					this._birthDate = value;
					this.SendPropertyChanged("birthDate");
					this.OnbirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(30)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this.OnsectionChanging(value);
					this.SendPropertyChanging();
					this._section = value;
					this.SendPropertyChanged("section");
					this.OnsectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Grading", DbType="NVarChar(30)")]
		public string First_Grading
		{
			get
			{
				return this._First_Grading;
			}
			set
			{
				if ((this._First_Grading != value))
				{
					this.OnFirst_GradingChanging(value);
					this.SendPropertyChanging();
					this._First_Grading = value;
					this.SendPropertyChanged("First_Grading");
					this.OnFirst_GradingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Grading", DbType="NVarChar(30)")]
		public string Second_Grading
		{
			get
			{
				return this._Second_Grading;
			}
			set
			{
				if ((this._Second_Grading != value))
				{
					this.OnSecond_GradingChanging(value);
					this.SendPropertyChanging();
					this._Second_Grading = value;
					this.SendPropertyChanged("Second_Grading");
					this.OnSecond_GradingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Third_Grading", DbType="NVarChar(30)")]
		public string Third_Grading
		{
			get
			{
				return this._Third_Grading;
			}
			set
			{
				if ((this._Third_Grading != value))
				{
					this.OnThird_GradingChanging(value);
					this.SendPropertyChanging();
					this._Third_Grading = value;
					this.SendPropertyChanged("Third_Grading");
					this.OnThird_GradingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fourth_Grading", DbType="NVarChar(30)")]
		public string Fourth_Grading
		{
			get
			{
				return this._Fourth_Grading;
			}
			set
			{
				if ((this._Fourth_Grading != value))
				{
					this.OnFourth_GradingChanging(value);
					this.SendPropertyChanging();
					this._Fourth_Grading = value;
					this.SendPropertyChanged("Fourth_Grading");
					this.OnFourth_GradingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy_f1", DbType="NVarChar(30)")]
		public string UpdatedBy_f1
		{
			get
			{
				return this._UpdatedBy_f1;
			}
			set
			{
				if ((this._UpdatedBy_f1 != value))
				{
					this.OnUpdatedBy_f1Changing(value);
					this.SendPropertyChanging();
					this._UpdatedBy_f1 = value;
					this.SendPropertyChanged("UpdatedBy_f1");
					this.OnUpdatedBy_f1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy_sc", DbType="NVarChar(30)")]
		public string UpdatedBy_sc
		{
			get
			{
				return this._UpdatedBy_sc;
			}
			set
			{
				if ((this._UpdatedBy_sc != value))
				{
					this.OnUpdatedBy_scChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy_sc = value;
					this.SendPropertyChanged("UpdatedBy_sc");
					this.OnUpdatedBy_scChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy_th", DbType="NVarChar(30)")]
		public string UpdatedBy_th
		{
			get
			{
				return this._UpdatedBy_th;
			}
			set
			{
				if ((this._UpdatedBy_th != value))
				{
					this.OnUpdatedBy_thChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy_th = value;
					this.SendPropertyChanged("UpdatedBy_th");
					this.OnUpdatedBy_thChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy_f4", DbType="NVarChar(30)")]
		public string UpdatedBy_f4
		{
			get
			{
				return this._UpdatedBy_f4;
			}
			set
			{
				if ((this._UpdatedBy_f4 != value))
				{
					this.OnUpdatedBy_f4Changing(value);
					this.SendPropertyChanging();
					this._UpdatedBy_f4 = value;
					this.SendPropertyChanged("UpdatedBy_f4");
					this.OnUpdatedBy_f4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_FirstG_Subject")]
	public partial class tbl_Student_FirstG_Subject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_firstG;
		
		private System.Nullable<double> _English_firstG;
		
		private System.Nullable<double> _Math_firstG;
		
		private System.Nullable<double> _Filipino_firstG;
		
		private System.Nullable<double> _Science_firstG;
		
		private System.Nullable<float> _Period_Avg_firstG;
		
		private string _Period_Status_firstG;
		
		private string _GradeStatus;
		
		private string _updatedBy;
		
		public tbl_Student_FirstG_Subject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_firstG", DbType="Float")]
		public System.Nullable<double> Mapeh_firstG
		{
			get
			{
				return this._Mapeh_firstG;
			}
			set
			{
				if ((this._Mapeh_firstG != value))
				{
					this._Mapeh_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_firstG", DbType="Float")]
		public System.Nullable<double> English_firstG
		{
			get
			{
				return this._English_firstG;
			}
			set
			{
				if ((this._English_firstG != value))
				{
					this._English_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_firstG", DbType="Float")]
		public System.Nullable<double> Math_firstG
		{
			get
			{
				return this._Math_firstG;
			}
			set
			{
				if ((this._Math_firstG != value))
				{
					this._Math_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_firstG", DbType="Float")]
		public System.Nullable<double> Filipino_firstG
		{
			get
			{
				return this._Filipino_firstG;
			}
			set
			{
				if ((this._Filipino_firstG != value))
				{
					this._Filipino_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_firstG", DbType="Float")]
		public System.Nullable<double> Science_firstG
		{
			get
			{
				return this._Science_firstG;
			}
			set
			{
				if ((this._Science_firstG != value))
				{
					this._Science_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_firstG", DbType="Real")]
		public System.Nullable<float> Period_Avg_firstG
		{
			get
			{
				return this._Period_Avg_firstG;
			}
			set
			{
				if ((this._Period_Avg_firstG != value))
				{
					this._Period_Avg_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_firstG", DbType="NVarChar(30)")]
		public string Period_Status_firstG
		{
			get
			{
				return this._Period_Status_firstG;
			}
			set
			{
				if ((this._Period_Status_firstG != value))
				{
					this._Period_Status_firstG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeStatus", DbType="NVarChar(30)")]
		public string GradeStatus
		{
			get
			{
				return this._GradeStatus;
			}
			set
			{
				if ((this._GradeStatus != value))
				{
					this._GradeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_FourthG_Subject")]
	public partial class tbl_Student_FourthG_Subject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_FourthG;
		
		private System.Nullable<double> _English_FourthG;
		
		private System.Nullable<double> _Math_FourthG;
		
		private System.Nullable<double> _Filipino_FourthG;
		
		private System.Nullable<double> _Science_FourthG;
		
		private System.Nullable<float> _Period_Avg_FourthG;
		
		private string _Period_Status_FourthG;
		
		private string _GradeStatus;
		
		private string _updatedBy;
		
		public tbl_Student_FourthG_Subject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_FourthG", DbType="Float")]
		public System.Nullable<double> Mapeh_FourthG
		{
			get
			{
				return this._Mapeh_FourthG;
			}
			set
			{
				if ((this._Mapeh_FourthG != value))
				{
					this._Mapeh_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_FourthG", DbType="Float")]
		public System.Nullable<double> English_FourthG
		{
			get
			{
				return this._English_FourthG;
			}
			set
			{
				if ((this._English_FourthG != value))
				{
					this._English_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_FourthG", DbType="Float")]
		public System.Nullable<double> Math_FourthG
		{
			get
			{
				return this._Math_FourthG;
			}
			set
			{
				if ((this._Math_FourthG != value))
				{
					this._Math_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_FourthG", DbType="Float")]
		public System.Nullable<double> Filipino_FourthG
		{
			get
			{
				return this._Filipino_FourthG;
			}
			set
			{
				if ((this._Filipino_FourthG != value))
				{
					this._Filipino_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_FourthG", DbType="Float")]
		public System.Nullable<double> Science_FourthG
		{
			get
			{
				return this._Science_FourthG;
			}
			set
			{
				if ((this._Science_FourthG != value))
				{
					this._Science_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_FourthG", DbType="Real")]
		public System.Nullable<float> Period_Avg_FourthG
		{
			get
			{
				return this._Period_Avg_FourthG;
			}
			set
			{
				if ((this._Period_Avg_FourthG != value))
				{
					this._Period_Avg_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_FourthG", DbType="NVarChar(30)")]
		public string Period_Status_FourthG
		{
			get
			{
				return this._Period_Status_FourthG;
			}
			set
			{
				if ((this._Period_Status_FourthG != value))
				{
					this._Period_Status_FourthG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeStatus", DbType="NVarChar(30)")]
		public string GradeStatus
		{
			get
			{
				return this._GradeStatus;
			}
			set
			{
				if ((this._GradeStatus != value))
				{
					this._GradeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_SecondG_Subject")]
	public partial class tbl_Student_SecondG_Subject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_SecondG;
		
		private System.Nullable<double> _English_SecondG;
		
		private System.Nullable<double> _Math_SecondG;
		
		private System.Nullable<double> _Filipino_SecondG;
		
		private System.Nullable<double> _Science_SecondG;
		
		private System.Nullable<float> _Period_Avg_SecondG;
		
		private string _Period_Status_SecondG;
		
		private string _GradeStatus;
		
		private string _updatedBy;
		
		public tbl_Student_SecondG_Subject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_SecondG", DbType="Float")]
		public System.Nullable<double> Mapeh_SecondG
		{
			get
			{
				return this._Mapeh_SecondG;
			}
			set
			{
				if ((this._Mapeh_SecondG != value))
				{
					this._Mapeh_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_SecondG", DbType="Float")]
		public System.Nullable<double> English_SecondG
		{
			get
			{
				return this._English_SecondG;
			}
			set
			{
				if ((this._English_SecondG != value))
				{
					this._English_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_SecondG", DbType="Float")]
		public System.Nullable<double> Math_SecondG
		{
			get
			{
				return this._Math_SecondG;
			}
			set
			{
				if ((this._Math_SecondG != value))
				{
					this._Math_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_SecondG", DbType="Float")]
		public System.Nullable<double> Filipino_SecondG
		{
			get
			{
				return this._Filipino_SecondG;
			}
			set
			{
				if ((this._Filipino_SecondG != value))
				{
					this._Filipino_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_SecondG", DbType="Float")]
		public System.Nullable<double> Science_SecondG
		{
			get
			{
				return this._Science_SecondG;
			}
			set
			{
				if ((this._Science_SecondG != value))
				{
					this._Science_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_SecondG", DbType="Real")]
		public System.Nullable<float> Period_Avg_SecondG
		{
			get
			{
				return this._Period_Avg_SecondG;
			}
			set
			{
				if ((this._Period_Avg_SecondG != value))
				{
					this._Period_Avg_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_SecondG", DbType="NVarChar(30)")]
		public string Period_Status_SecondG
		{
			get
			{
				return this._Period_Status_SecondG;
			}
			set
			{
				if ((this._Period_Status_SecondG != value))
				{
					this._Period_Status_SecondG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeStatus", DbType="NVarChar(30)")]
		public string GradeStatus
		{
			get
			{
				return this._GradeStatus;
			}
			set
			{
				if ((this._GradeStatus != value))
				{
					this._GradeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Student_ThirdG_Subject")]
	public partial class tbl_Student_ThirdG_Subject
	{
		
		private System.Nullable<int> _FK_studentID;
		
		private System.Nullable<double> _Mapeh_ThirdG;
		
		private System.Nullable<double> _English_ThirdG;
		
		private System.Nullable<double> _Math_ThirdG;
		
		private System.Nullable<double> _Filipino_ThirdG;
		
		private System.Nullable<double> _Science_ThirdG;
		
		private System.Nullable<float> _Period_Avg_ThirdG;
		
		private string _Period_Status_ThirdG;
		
		private string _GradeStatus;
		
		private string _updatedBy;
		
		public tbl_Student_ThirdG_Subject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_studentID", DbType="Int")]
		public System.Nullable<int> FK_studentID
		{
			get
			{
				return this._FK_studentID;
			}
			set
			{
				if ((this._FK_studentID != value))
				{
					this._FK_studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mapeh_ThirdG", DbType="Float")]
		public System.Nullable<double> Mapeh_ThirdG
		{
			get
			{
				return this._Mapeh_ThirdG;
			}
			set
			{
				if ((this._Mapeh_ThirdG != value))
				{
					this._Mapeh_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English_ThirdG", DbType="Float")]
		public System.Nullable<double> English_ThirdG
		{
			get
			{
				return this._English_ThirdG;
			}
			set
			{
				if ((this._English_ThirdG != value))
				{
					this._English_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math_ThirdG", DbType="Float")]
		public System.Nullable<double> Math_ThirdG
		{
			get
			{
				return this._Math_ThirdG;
			}
			set
			{
				if ((this._Math_ThirdG != value))
				{
					this._Math_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filipino_ThirdG", DbType="Float")]
		public System.Nullable<double> Filipino_ThirdG
		{
			get
			{
				return this._Filipino_ThirdG;
			}
			set
			{
				if ((this._Filipino_ThirdG != value))
				{
					this._Filipino_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science_ThirdG", DbType="Float")]
		public System.Nullable<double> Science_ThirdG
		{
			get
			{
				return this._Science_ThirdG;
			}
			set
			{
				if ((this._Science_ThirdG != value))
				{
					this._Science_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Avg_ThirdG", DbType="Real")]
		public System.Nullable<float> Period_Avg_ThirdG
		{
			get
			{
				return this._Period_Avg_ThirdG;
			}
			set
			{
				if ((this._Period_Avg_ThirdG != value))
				{
					this._Period_Avg_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period_Status_ThirdG", DbType="NVarChar(30)")]
		public string Period_Status_ThirdG
		{
			get
			{
				return this._Period_Status_ThirdG;
			}
			set
			{
				if ((this._Period_Status_ThirdG != value))
				{
					this._Period_Status_ThirdG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeStatus", DbType="NVarChar(30)")]
		public string GradeStatus
		{
			get
			{
				return this._GradeStatus;
			}
			set
			{
				if ((this._GradeStatus != value))
				{
					this._GradeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(50)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this._updatedBy = value;
				}
			}
		}
	}
	
	public partial class SP_View_TeacherAccResult
	{
		
		private int _Teacher_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Passowrd;
		
		public SP_View_TeacherAccResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Teacher ID]", Storage="_Teacher_ID", DbType="Int NOT NULL")]
		public int Teacher_ID
		{
			get
			{
				return this._Teacher_ID;
			}
			set
			{
				if ((this._Teacher_ID != value))
				{
					this._Teacher_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passowrd", DbType="NVarChar(50)")]
		public string Passowrd
		{
			get
			{
				return this._Passowrd;
			}
			set
			{
				if ((this._Passowrd != value))
				{
					this._Passowrd = value;
				}
			}
		}
	}
	
	public partial class SP_stud_Ranking_FirstGradingResult
	{
		
		private int _studentID;
		
		private string _Full_Name;
		
		private System.Nullable<float> _Average;
		
		public SP_stud_Ranking_FirstGradingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this._studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Average", DbType="Real")]
		public System.Nullable<float> Average
		{
			get
			{
				return this._Average;
			}
			set
			{
				if ((this._Average != value))
				{
					this._Average = value;
				}
			}
		}
	}
	
	public partial class SP_stud_Ranking_ThirdGradingResult
	{
		
		private int _studentID;
		
		private string _Full_Name;
		
		private System.Nullable<float> _Average;
		
		public SP_stud_Ranking_ThirdGradingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this._studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Average", DbType="Real")]
		public System.Nullable<float> Average
		{
			get
			{
				return this._Average;
			}
			set
			{
				if ((this._Average != value))
				{
					this._Average = value;
				}
			}
		}
	}
	
	public partial class SP_stud_Ranking_FourthGradingResult
	{
		
		private int _studentID;
		
		private string _Full_Name;
		
		private System.Nullable<float> _Average;
		
		public SP_stud_Ranking_FourthGradingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this._studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Average", DbType="Real")]
		public System.Nullable<float> Average
		{
			get
			{
				return this._Average;
			}
			set
			{
				if ((this._Average != value))
				{
					this._Average = value;
				}
			}
		}
	}
	
	public partial class SP_stud_Ranking_SecondGradingResult
	{
		
		private int _studentID;
		
		private string _Full_Name;
		
		private System.Nullable<float> _Average;
		
		public SP_stud_Ranking_SecondGradingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this._studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Average", DbType="Real")]
		public System.Nullable<float> Average
		{
			get
			{
				return this._Average;
			}
			set
			{
				if ((this._Average != value))
				{
					this._Average = value;
				}
			}
		}
	}
	
	public partial class SP_stud_ViewLIstResult
	{
		
		private int _studentId;
		
		private string _Full_Name;
		
		private System.DateTime _BirthDate;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<int> _Grade;
		
		private string _Section;
		
		private string _CreatedBy;
		
		public SP_stud_ViewLIstResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", DbType="Int NOT NULL")]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this._studentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date NOT NULL")]
		public System.DateTime BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="NVarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
	}
	
	public partial class SP_stud_ViewStudentsResult
	{
		
		private int _studentId;
		
		private string _Full_Name;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<int> _Grade;
		
		private string _Section;
		
		private string _First_Grading_Uptd_by;
		
		private string _Second_Grading_Uptd_by;
		
		private string _Third_Grading_Uptd_by;
		
		private string _Fourth_Grading_Uptd_by;
		
		public SP_stud_ViewStudentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", DbType="Int NOT NULL")]
		public int studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					this._studentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(153) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="NVarChar(30)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Grading|Uptd by]", Storage="_First_Grading_Uptd_by", DbType="NVarChar(63) NOT NULL", CanBeNull=false)]
		public string First_Grading_Uptd_by
		{
			get
			{
				return this._First_Grading_Uptd_by;
			}
			set
			{
				if ((this._First_Grading_Uptd_by != value))
				{
					this._First_Grading_Uptd_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Second Grading|Uptd by]", Storage="_Second_Grading_Uptd_by", DbType="NVarChar(63) NOT NULL", CanBeNull=false)]
		public string Second_Grading_Uptd_by
		{
			get
			{
				return this._Second_Grading_Uptd_by;
			}
			set
			{
				if ((this._Second_Grading_Uptd_by != value))
				{
					this._Second_Grading_Uptd_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Third Grading|Uptd by]", Storage="_Third_Grading_Uptd_by", DbType="NVarChar(63) NOT NULL", CanBeNull=false)]
		public string Third_Grading_Uptd_by
		{
			get
			{
				return this._Third_Grading_Uptd_by;
			}
			set
			{
				if ((this._Third_Grading_Uptd_by != value))
				{
					this._Third_Grading_Uptd_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fourth Grading|Uptd by]", Storage="_Fourth_Grading_Uptd_by", DbType="NVarChar(63) NOT NULL", CanBeNull=false)]
		public string Fourth_Grading_Uptd_by
		{
			get
			{
				return this._Fourth_Grading_Uptd_by;
			}
			set
			{
				if ((this._Fourth_Grading_Uptd_by != value))
				{
					this._Fourth_Grading_Uptd_by = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
